[workspace]
members = ["crates/*", "poc-parsers/*"]
resolver = "2"

[workspace.dependencies]
ropey = "1.6.0"
tracing = { version = "0.1.37", features = ["log"] }
tracing-test = "0.2.4"
tree-sitter = "0.20.10"
tree-sitter-ruby = "0.20.0"
